### ISSUE TITLE
Undefined text appears when invoice is created!

### ISSUE THREAD

**Issue by Muzorm** [Envi-Scripts/envi-receipts#4]
We've installed the script, but we're having trouble integrating the qb inv app.js part. After the receipt is created, the description of the receipt doesn't appear in the inventory. When we use the receipt, nothing shows up on the receipt.
![Screenshot_1](https://github.com/Envi-Scripts/envi-receipts/assets/123986261/1cdb7afb-e32c-4169-aaae-30983de6b7dd)
![image](https://github.com/Envi-Scripts/envi-receipts/assets/123986261/e66a73ce-0efd-4c75-b16f-e47ad9f827f3)
![image](https://github.com/Envi-Scripts/envi-receipts/assets/123986261/1f890815-143b-4143-bea2-ed9204f9c39d)

**Comment by Envi-Scripts** [comment]
doesnt seem related to that, open a ticket on discord we'll get you sorted :)
